---

- hosts: localhost
  gather_facts: false
  ansible_connection: local
  tasks:
    - name: Generate Terraform Infra vars
      template:
        src: secret.auto.tfvars.j2
        dest: '../terraform/secret.auto.tfvars'
    - name: Generate Terraform Backend vars
      template:
        src: secret.backend.tfvars.j2
        dest: '../terraform/secret.backend.tfvars'
